EStringType = 
{
    
    --game
    ["EST_GAME_SCORES"]     = "EST_GAME_SCORES";
    
    --game over
    ["EST_POPUP_GAME_OVER_TITLE"]           = "EST_POPUP_GAME_OVER_TITLE";
    ["EST_POPUP_GAME_OVER_BUTTON_CLOSE"]    = "EST_POPUP_GAME_OVER_BUTTON_CLOSE";
    
    --win
    ["EST_POPUP_WIN_TITLE"]                 = "EST_POPUP_WIN_TITLE";
    ["EST_POPUP_WIN_TEXT"]                  = "EST_POPUP_WIN_TEXT";
    ["EST_POPUP_WIN_BUTTON_CLOSE"]          = "EST_POPUP_WIN_BUTTON_CLOSE";
    
    --pause
    ["EST_POPUP_PAUSE_TITLE"]               = "EST_POPUP_PAUSE_TITLE";
    ["EST_POPUP_PAUSE_BUTTON_CLOSE"]        = "EST_POPUP_PAUSE_BUTTON_CLOSE";
    ["EST_POPUP_PAUSE_BUTTON_REPLAY"]       = "EST_POPUP_PAUSE_BUTTON_REPLAY";
    
    --shop
    ["EST_POPUP_SHOP_BUTTON_CLOSE"]         = "EST_POPUP_SHOP_BUTTON_CLOSE";
    ["EST_POPUP_SHOP_TITLE"]                = "EST_POPUP_SHOP_TITLE";
    ["EST_POPUP_SHOP_BUTTON_ENERGY"]        = "EST_POPUP_SHOP_BUTTON_ENERGY";
    ["EST_POPUP_SHOP_BUTTON_PURCHASE"]      = "EST_POPUP_SHOP_BUTTON_PURCHASE";
    ["EST_POPUP_SHOP_BUTTON_BUY"]           = "EST_POPUP_SHOP_BUTTON_BUY";
}

